package pojo;
// Generated 18-Oct-2020 20:19:13 by Hibernate Tools 4.3.1

import DAO.DAOBarang;
import DAO.DAOTransaksi;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;




/**
 * TblTransaksi generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class TblTransaksi  implements java.io.Serializable {
    
    FacesContext context2 = FacesContext.getCurrentInstance();
    HttpSession session = (HttpSession) context2.getExternalContext().getSession(true);


     private String idTransaksi;
     private String idBarang ;
     private String namaBarang;
     private String namaPenerima;
     private String alamatPenerima;
     private String notelpPenerima;
     private String tglTransaksi;
     private String idSeller = (String) session.getAttribute("user");
     private String tgl,date;
     private int jumlahPembelian;


    public TblTransaksi() {
        LocalDate dateobj = LocalDate.now();
        DateTimeFormatter dateformat = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        date = dateobj.format(dateformat);    
        tglTransaksi = date;
    }

    public TblTransaksi(int jumlahPembelian, String idTransaksi, String idBarang, String namaBarang, String namaPenerima, String alamatPenerima, String notelpPenerima, String tglTransaksi, String idSeller) {
       this.idTransaksi = idTransaksi;
       this.idBarang = idBarang;
       this.namaBarang = namaBarang;
       this.namaPenerima = namaPenerima;
       this.alamatPenerima = alamatPenerima;
       this.notelpPenerima = notelpPenerima;
       this.tglTransaksi = tglTransaksi;
       this.idSeller = idSeller;
       this.jumlahPembelian = jumlahPembelian;
    }

    public int getJumlahPembelian() {
        return jumlahPembelian;
    }

    public void setJumlahPembelian(int jumlahPembelian) {
        this.jumlahPembelian = jumlahPembelian;
    }
    
    
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getIdSeller() {
        return idSeller;
    }

    public void setIdSeller(String idSeller) {
        this.idSeller = idSeller;
    }

    public String getTgl() {
        return tgl;
    }

    public void setTgl(String tgl) {
        this.tgl = tgl;
    }
    
    public String getIdTransaksi() {
        return this.idTransaksi;
    }
    
    public void setIdTransaksi(String idTransaksi) {
        this.idTransaksi = idTransaksi;
    }
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public String getNamaPenerima() {
        return this.namaPenerima;
    }
    
    public void setNamaPenerima(String namaPenerima) {
        this.namaPenerima = namaPenerima;
    }
    public String getAlamatPenerima() {
        return this.alamatPenerima;
    }
    
    public void setAlamatPenerima(String alamatPenerima) {
        this.alamatPenerima = alamatPenerima;
    }
    public String getNotelpPenerima() {
        return this.notelpPenerima;
    }
    
    public void setNotelpPenerima(String notelpPenerima) {
        this.notelpPenerima = notelpPenerima;
    }
    public String getTglTransaksi() {
        return this.tglTransaksi;
    }
    
    public void setTglTransaksi(String tglTransaksi) {
        this.tglTransaksi = tglTransaksi;
    }
    
    
    public String cariData(){
        DAOTransaksi dao = new DAOTransaksi();
        List<TblTransaksi> list = dao.cariID(idTransaksi);
        
        idBarang = list.get(0).idBarang;
        namaBarang = list.get(0).namaBarang;
        namaPenerima = list.get(0).namaPenerima;
        alamatPenerima = list.get(0).alamatPenerima;
        notelpPenerima = list.get(0).notelpPenerima;
        tglTransaksi = list.get(0).tglTransaksi;
        return "product";
    }
    
    public List<TblTransaksi> getallrecord(){
        DAOTransaksi dao = new DAOTransaksi();
        List<TblTransaksi> list = dao.retrieveTblTransaksi();
        return list;
    }
    
    public void tglan(){
        DAOTransaksi dao = new DAOTransaksi();
        List<TblTransaksi> list = dao.allrecordReverse(idSeller);
        if(list.isEmpty()){
            tgl = "Tidak Ada Transaksi";
        } else {
            tgl = list.get(0).tglTransaksi;
        } 
    }
    
    public List<TblTransaksi> allRecordById(){
        DAOTransaksi dao = new DAOTransaksi();
        List<TblTransaksi> list = dao.getDataById(idSeller);
        return list;
    }
    
    public String dataTrx(String idbar) {
        DAOBarang dao = new DAOBarang();
        List<TblBarang> list = dao.cariID(idbar);
        idBarang = list.get(0).getIdBarang();
        namaBarang = list.get(0).getNamaBarang();
        idSeller = list.get(0).getIdSeller();
        return "addtransaksi?faces-redirect=true";
    }
    
      public String addtransaksi() {
        DAOTransaksi dao = new DAOTransaksi();
        List<TblTransaksi> list = dao.transid(idTransaksi);
        
        if(list.size()==0){
            TblBarang tbl = new TblBarang();
            dao.addTransaksi(this);
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("jumlah", jumlahPembelian);
            FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("idbar", idBarang);
            tbl.itung();
            return "transaksi?faces-redirect=true";
        } else {
           idTransaksi = "";
           return "addtransaksi";
        }
    }
     
}


